//Navigation const
export const SIDE_DRAWER_TOGGLE = "SIDE_DRAWER_TOGGLE";
export const SIDE_DRAWER_OFF = "SIDE_DRAWER_OFF";

//ItemsCart const
export const MODAL_TOGGLE_ON = "MODAL_TOGGLE_ON";
export const MODAL_TOGGLE_OFF = "MODAL_TOGGLE_OFF";
export const SELECTED_PIZZA = "SELECTED_PIZZA";
export const CURRENT_PIZZA_SIZE = "CURRENT_PIZZA_SIZE";
export const RESET_PIZZA_SIZE = "RESET_PIZZA_SIZE";

export const INFO_ABOUT_PRODUCT = "INFO_ABOUT_PRODUCT";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_ONE_MORE_CART = "ADD_ONE_MORE_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const SUBMIT_ORDER = "SUBMIT_ORDER";
export const RESET_ITEMS_FROM_CART = "RESET_ITEMS_FROM_CART";

//auth const
export const SET_USER = "SET_USER";
export const SIGN_OUT = "SIGN_OUT";
